#
# Copyright (C) 2025 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/alps/FRT

# Build Broken Rules
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
BUILD_BROKEN_MISSING_REQUIRED_MODULES := true
BUILD_BROKEN_VENDOR_PROPERTY_NAMESPACE := true

DEXPREOPT_GENERATE_APEX_IMAGE := true

# Architecture (32-bit for Nokia 1)
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a53

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := FRT
TARGET_NO_BOOTLOADER := true

# Boot Image
BOARD_BOOTIMG_HEADER_VERSION := 2
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,32N2 buildvariant=userdebug
BOARD_KERNEL_CMDLINE += androidboot.init_fatal_reboot_target=recovery
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x04000000
BOARD_KERNEL_TAGS_OFFSET := 0xE000000
BOARD_DTB_OFFSET := 0x0e000000

BOARD_INCLUDE_DTB_IN_BOOTIMG := true

BOARD_MKBOOTIMG_ARGS := --base $(BOARD_KERNEL_BASE)
BOARD_MKBOOTIMG_ARGS += --kernel_offset $(BOARD_KERNEL_OFFSET)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --dtb_offset $(BOARD_DTB_OFFSET)
BOARD_MKBOOTIMG_ARGS += --pagesize $(BOARD_KERNEL_PAGESIZE)
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)


# Display
TARGET_SCREEN_DENSITY := 240

# Kernel
TARGET_KERNEL_ARCH := arm
TARGET_KERNEL_HEADER_ARCH := arm

TARGET_FORCE_PREBUILT_KERNEL := true

ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
    TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/zImage-dtb
    BOARD_KERNEL_IMAGE_NAME := zImage-dtb
    BOARD_INCLUDE_DTB_IN_BOOTIMG := true

    # Fake install dtb.img to prevent build failure
    INSTALLED_DTBIMAGE_TARGET := $(PRODUCT_OUT)/dtb.img
    PRODUCT_COPY_FILES += \
        $(DEVICE_PATH)/prebuilts/dtb.img:dtb.img
endif

# DTBO image for devices with separate DTBO partition
BOARD_KERNEL_SEPARATED_DTBO := true
TARGET_PREBUILT_DTBO := $(DEVICE_PATH)/dtbo/dtbo.img
INSTALLED_DTBOIMAGE_TARGET := $(PRODUCT_OUT)/dtbo.img

$(INSTALLED_DTBOIMAGE_TARGET): $(DEVICE_PATH)/dtbo/dtbo.img
	@echo "Using prebuilt dtbo.img"
	cp -f $< $@


# Partitions
BOARD_FLASH_BLOCK_SIZE := 131072  # (128KB)

# Partition Sizes
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216        # 16MB
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1634066432    # Aligned to 16MB
BOARD_VENDORIMAGE_PARTITION_SIZE := 335544320     # Aligned to 16MB
BOARD_DATAIMAGE_PARTITION_SIZE := 5474615296      # Aligned to 16MB
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 17936384
BOARD_DTBOIMG_PARTITION_SIZE := 8388608

# Filesystem Types
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_DATAIMAGE_FILE_SYSTEM_TYPE := ext4

TARGET_COPY_OUT_VENDOR := vendor

# Platform
TARGET_BOARD_PLATFORM := mt6735m
BOARD_HAS_MTK_HARDWARE := true

# HIDL
DEVICE_MANIFEST_FILE += $(DEVICE_PATH)/manifest.xml
DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE := $(DEVICE_PATH)/framework_compatibility_matrix.xml

# Properties
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop
TARGET_PRODUCT_PROP += $(DEVICE_PATH)/product.prop
TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop
TARGET_ODM_PROP += $(DEVICE_PATH)/odm.prop

# Recovery
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/etc/fstab.mt6735m
TARGET_USERIMAGES_USE_EXT4 := true
#TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888

# SELinux
#BOARD_VENDOR_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/vendor
#SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/private

# Verified Boot
BOARD_AVB_ENABLE := true  # Disable for older devices
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --set_hashtree_disabled_flag
BOARD_AVB_DTBO_ADD_HASH_FOOTER_ARGS := --partition_name odmdtbo

# Security Patch
VENDOR_SECURITY_PATCH := 2021-04-05

# Inherit vendor
include vendor/alps/FRT/BoardConfigVendor.mk
